const opportunitiesData: object = {
  activeOpportunities: [
    {
      id: 1,
      isChecked: false,
      name: "Front-End Developer",
      applicantsApplied: 5,
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "25 days (remaining)",
      oppCreated: "14/08/2019",
      oppStatus: "Active",
    },
    {
      id: 2,
      isChecked: false,
      name: "Back-End Developer",
      applicantsApplied: 12,
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "25 days (remaining)",
      oppCreated: "14/08/2019",
      oppStatus: "Active",
    },
  ],
  draftOpportunities: [
    {
      id: 1,
      isChecked: false,
      name: "Junior Front-End Developer",
      applicantsApplied: "-",
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "-",
      oppCreated: "14/08/2019",
      oppStatus: "Draft",
    },
  ],
  closedOpportunities: [
    {
      id: 1,
      isChecked: false,
      name: "Full-stack Developer",
      applicantsApplied: "24",
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "Expired",
      oppCreated: "14/08/2019",
      oppStatus: "Closed",
    },
  ],
  singleOppDetails: {
    appliedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Review Talent",
      },
      {
        id: 2,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Shehroz Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "92%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Review Talent",
      },
      {
        id: 3,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Majid Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "81%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Review Talent",
      },
      {
        id: 4,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Ahmad Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "62%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Review Talent",
      },
      {
        id: 5,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Maratib Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "42%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Review Talent",
      },
      {
        id: 6,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Abubakr Tanveer ",
        oppApplyingFor: "Front-End Developer",
        match: "17%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Review Talent",
      },
    ],
    shortListedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Shortlisted",
      },
      {
        id: 2,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Shehroz Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "92%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Shortlisted",
      },
      {
        id: 3,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Majid Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "81%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Shortlisted",
      },
    ],
    invitedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Invited",
      },
    ],
    acceptedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Accepted ",
      },
    ],
    rejectedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Majid Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "81%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Rejected",
      },
      {
        id: 2,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Ahmad Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "62%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Rejected",
      },
      {
        id: 3,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Maratib Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "42%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Rejected",
      },
      {
        id: 4,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Abubakr Tanveer ",
        oppApplyingFor: "Front-End Developer",
        match: "17%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Rejected",
      },
    ],
  },
};

export default opportunitiesData;
