const opportunitiesData: object = {
  activeOpportunities: [
    {
      id: 1,
      isChecked: false,
      name: "Front-End Developer",
      applicantsApplied: 5,
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "25 days (remaining)",
      oppCreated: "14/08/2019",
      oppStatus: "Active",
    },
    {
      id: 2,
      isChecked: false,
      name: "Back-End Developer",
      applicantsApplied: 12,
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "25 days (remaining)",
      oppCreated: "14/08/2019",
      oppStatus: "Active",
    },
  ],
  draftOpportunities: [
    {
      id: 1,
      isChecked: false,
      name: "Junior Front-End Developer",
      applicantsApplied: "-",
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "-",
      oppCreated: "14/08/2019",
      oppStatus: "Draft",
    },
  ],
  closedOpportunities: [
    {
      id: 1,
      isChecked: false,
      name: "Full-stack Developer",
      applicantsApplied: "24",
      fieldOfOccupation: "Web, Mobile & Software Development",
      oppDuration: "Expired",
      oppCreated: "14/08/2019",
      oppStatus: "Closed",
    },
  ],
  singleOppDetails: {
    appliedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Review Talent",
      },
      {
        id: 2,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Shehroz Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "92%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Review Talent",
      },
      {
        id: 3,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Majid Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "81%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Review Talent",
      },
      {
        id: 4,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Ahmad Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "62%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Review Talent",
      },
      {
        id: 5,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Maratib Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "42%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Review Talent",
      },
      {
        id: 6,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Abubakr Tanveer ",
        oppApplyingFor: "Front-End Developer",
        match: "17%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Review Talent",
      },
    ],
    shortListedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Shortlisted",
      },
      {
        id: 2,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Shehroz Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "92%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Shortlisted",
      },
      {
        id: 3,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Majid Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "81%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Shortlisted",
      },
    ],
    invitedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Invited",
      },
    ],
    acceptedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Waleed Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "95%",
        dateApplied: "14/08/2019",
        remainingTime: "7 days to respond",
        status: "Accepted ",
      },
    ],
    rejectedApplicants: [
      {
        id: 1,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Majid Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "81%",
        dateApplied: "13/08/2019",
        remainingTime: "6 days to respond",
        status: "Rejected",
      },
      {
        id: 2,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Ahmad Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "62%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Rejected",
      },
      {
        id: 3,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Maratib Ali Khan",
        oppApplyingFor: "Front-End Developer",
        match: "42%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Rejected",
      },
      {
        id: 4,
        applicantImg: "/img/icons/gallery-icon.svg",
        isChecked: false,
        fullName: "Abubakr Tanveer ",
        oppApplyingFor: "Front-End Developer",
        match: "17%",
        dateApplied: "12/08/2019",
        remainingTime: "5 days to respond",
        status: "Rejected",
      },
    ],
  },
  singleOppView: {
    oppViewHeader: {
      companyImgUrl: "/img/companies/pixel-&-graph-large.svg",
      oppTitle: "Front-End Developer",
      companyName: "Pixel & Graphs",
      oppRemainingTime: "30 days remaining - ends on 14/08/2019",
      fieldOfOccupation: "Web, Mobile & Software Development",
    },
    oppViewWhoWeAre: [
      "One of our company goals has always been to create a workplace where developers can quickly grow their professional careers and use all of their skills to create innovative products, software, apps, and websites. We've come really close because we aren't growing the team with 'lone wolves', but developers who want to learn something new, who want to share that knowledge with others and who are ready to jump into that problem-solving mode whenever the encounter any kind of challenge. And, of course, have fun while they're doing it!",
      "Right now, we have 31 members in our Development department. That's 31 amazing minds who can look at a project from countless sides to find the right way to deliver the best result. And if their primary stack of PHP with Symfony, MySQL and JavaScript aren't enough to crack the issue, they'll learn a new language & use new tech - anything that'll make their job easier and themselves more proficient.",
    ],
    oppViewLocationWage: {
      location: "United Kingdom",
      salary: "$40.000 - $60.000",
    },
    oppViewTalentDetails: {
      talentLocation: ["UnitedStates", "United Kingdom"],
      talentWorkTimeFrom: "GMT+2",
      talentWorkTimeTo: "GMT+8",
    },
    oppViewDesc: [
      "Fuseproject is looking for a Freelance Lead Digital UI Designer in our Experience Design team, who is creative, passionate, and unwilling to compromise their drive to create stunning and engaging designed experiences that make a difference to our clients, their brand, and their customers.",
      "We work in a multidisciplinary environment and look for every opportunity to merge thinking and creative output. Our process, skillsets, and outputs are a function of our broad disciplines. We are looking for a freelancer to bring exceptional creative thought and craft output.",
      "The Freelance Lead Digital UI Designer takes an active, hands-on role in leading ideation to concept design through to detail design and into implementation. They are a passionate advocate for rigor and discipline in the design process yet operate freely and conceptually when considering design solutions. This important role requires broad knowledge and advanced skills in visual design, user experience, user interface, and a solid understanding of available client-side technologies.",
      "Successful Freelancer will have industry leading work examples across digital products and platforms, apps, websites, motion, CG and traditional graphic design. They will push the state-of-the-art and challenge convention with every creation and thrive in our fast-paced studio.",
    ],
    oppViewWhatToDo: [
      "Plan, structure and implement applications, websites, APIs, databases, etc.",
      "Develop medium-sized and large web-based projects",
      "Give your input and actively participate in various brainstormings",
      "Maintain active applications",
      "Define daily responsibilities and tasks with Project Managers and team members",
      "Collaborate with the members of the Quality Assurance team",
      "Work and experiment with trending technologies",
    ],
    oppRequiredSkills: [
      {
        id: 1,
        skill: "HTML (+5 years)",
        skillBg: "bg-skills-skill1",
      },
      {
        id: 2,
        skill: "CSS (+5 years)",
        skillBg: "bg-skills-skill2",
      },
      {
        id: 3,
        skill: "Javascript: Angular (+3 years)",
        skillBg: "bg-skills-skill3",
      },
      {
        id: 4,
        skill: "Javascript: React (+3 years)",
        skillBg: "bg-skills-skill4",
      },
      {
        id: 5,
        skill: "Javascript: Node.js (+3 years)",
        skillBg: "bg-skills-skill5",
      },
      {
        id: 6,
        skill: "PHP (+3 years)",
        skillBg: "bg-skills-skill1",
      },
      {
        id: 7,
        skill: "Ruby (+2 years)",
        skillBg: "bg-skills-skill2",
      },
      {
        id: 8,
        skill: "Python (+2 years)",
        skillBg: "bg-skills-skill3",
      },
    ],
    oppBonusSkills: [
      {
        id: 1,
        skill: "HTML (+5 years)",
        skillBg: "bg-skills-skill1",
      },
      {
        id: 2,
        skill: "CSS (+5 years)",
        skillBg: "bg-skills-skill2",
      },
      {
        id: 3,
        skill: "Javascript: Angular (+3 years)",
        skillBg: "bg-skills-skill3",
      },
      {
        id: 4,
        skill: "Javascript: React (+3 years)",
        skillBg: "bg-skills-skill4",
      },
      {
        id: 5,
        skill: "Javascript: Node.js (+3 years)",
        skillBg: "bg-skills-skill5",
      },
      {
        id: 6,
        skill: "PHP (+3 years)",
        skillBg: "bg-skills-skill1",
      },
      {
        id: 7,
        skill: "Ruby (+2 years)",
        skillBg: "bg-skills-skill2",
      },
      {
        id: 8,
        skill: "Python (+2 years)",
        skillBg: "bg-skills-skill3",
      },
    ],
  },
};

export default opportunitiesData;
